### ISSUE TITLE
Well done

### ISSUE THREAD

**Issue by maziac** [andrivet/ZX81-Debugger#5]
Hi, 
I just stumbled about your zx81-debugger.
I never thought that someone is able to understand my code to extend it in this great way.
Great stuff!

Actually, I was also thinking all the time to add a view for simulating the zx81.
But I think you already filled the gap very well. So, I don't have to do it anymore.

And I guess for the user the zx81-debugger is much easier to setup then the dezog is, as it has the assembler and the syntax highlighting already integrated.

Well done and sorry that I opened an issue, but I don't know how to get in touch in another way,
Maziac

**Comment by andrivet** [comment]
This very nice. Thank you.
