### ISSUE TITLE
How to set launch configurations for both source and binary?

### ISSUE THREAD

**Issue by city41** [andrivet/ZX81-Debugger#7]
This debugger is so awesome. Thanks to you and maziac!

I've noticed there is an option for launching a binary, and I can get that working with this launch config

```json
        {
            "type": "zx81debugger",
            "request": "launch",
            "name": "emulate binary",
            "rootFolder": "${workspaceFolder}",
            "binary": "${file}",
            "remoteType": "zsim"
        }
```

And with the binary focused in vscode, launching this launch config gets it running in the emulator as expected.

But then I can't seem to launch source files anymore. When I try, it errors saying the file is not a `.P`. 

I tried to add an additional launch config for source

```json
        {
            "type": "zx81debugger",
            "request": "launch",
            "name": "emulate source",
            "rootFolder": "${workspaceFolder}",
            "remoteType": "zsim"
        }
```

but since `"source"` is not an allowed config option, launching this config with a source file focused causes it to hang. 

The only way I've been about to get source files to debug is by removing my launch.json altogether to go back to the default workflow. Is there a way I can do both source and binary debugging in the same vscode project?

**Comment by andrivet** [comment]
The debugger will either compile (assemble) a source file and load the generated binary or will load a binary (for example if you do not have the sources) and disassemble it. It is not made to combine the two. In fact, I do not understand well your use case.

**Comment by city41** [comment]
Yeah I realize now my use case might be pretty obscure. I have a project that has both assembly source (things I am writing) and binaries (things other people have written that I'm trying to reverse engineer), and I was hoping to be able to launch either type in the same project.

But I totally understand that's probably not how most people would use a tool like this.

**Comment by andrivet** [comment]
"binary" does not exist. To compile from sources and load also other binaries, you can you can use "loadObjs". Your launch.json will be something like:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "zx81debugger",
            "request": "launch",
            "name": "ZX81 - Simulator",
            "remoteType": "zsim",
            "startAutomatically": false,
            "rootFolder": "${workspaceFolder}",
            "source": "${workspaceFolder}/some-sources.zx81",
            "loadObjs": [
                {
                    "path": "${workspaceFolder}/some-binary,
                    "start": "1234"
                }
            ]
        }
    ]
}
```

**Comment by city41** [comment]
binary does exist, but maybe unintentionally? Here is how to debug a binary. I'm using the ZX81-Debugger in the vs code marketplace and the sample hello.zx81 source.

1. Focus on hello.zx81 and press F5 to start debugging it normally
2. Stop this debugging session.
3. Create a launch.json file and add a launch configuration of
```
{
  "type": "zx81debugger",
  "request": "launch",
  "name": "emulate binary",
  "rootFolder": "${workspaceFolder}",
  "binary": "${file}",
  "remoteType": "zsim"
}
```
4. Focus on hello.P, head to the debug tab, choose "emulate binary" in the dropdown, and press play to start

You will then be debugging the binary version of hello, with the disassembled source

![image](https://github.com/user-attachments/assets/5de6b05b-0fa3-4ba0-bb75-06299da1f6e7)

Maybe you didn't intend for this to work like this but it's a very awesome feature :)

**Comment by andrivet** [comment]
Yes, you're right. I forgot that I had this option in the past and also no loadObjs. It is in my current development sources.

**Comment by city41** [comment]
Ah interesting. Ok. Anyway, I'd argue the issue I originally posted here either isn't a bug or a very obscure one so probably not worth looking into.

**Comment by andrivet** [comment]
This is added in (future) version 2.0.0. It will be possible to load any memory dump. The syntax is something like:

```
"source": "main.zx81",
"binaries": [
  {
    "path": "dump1.bin",
    "start": "1234"
  }
]
```
