### ISSUE TITLE
Labels not showing up in call stack, can't be used in watches

### ISSUE THREAD

**Issue by city41** [andrivet/ZX81-Debugger#8]
I noticed in version 1.3.1 that labels beyond system variables don't seem to work

![image](https://github.com/user-attachments/assets/a8236f11-fb6c-4cde-8d6f-8643d685a5e2)

In this screenshot I'm expecting the call stack to be

```
dispstring
__MAIN__
```

But instead it shows `dipsstring`'s address.

Watches that use labels don't work either, also shown in the screenshot.

I'm currently hacking on the debugger myself, and so I am trying to root cause and hopefully fix this. If I figure it out, I can send a PR if you would like. Let me know what you think.

**Comment by city41** [comment]
I may have fixed this? Here is what I did

In z80-assembler's Generate.ts, I added this lie

```diff
       // If it is not a statement, take the next line.
       // Si ce n'est pas une déclaration, on passe à la ligne suivante,
       if (line.kind !== ASTKinds.LineStatement || !line.statement) {
+        sld += generateSld(info.filename, lineNumber, address, line);
         lineNumber += 1; // Next line
         continue;
       }
```

I then rebuilt off of the 1.3.0 tag and then installed the artifacts directly into my node_modules as a crude test. So far it's working great. I can debug and run programs just fine, and labels work.

BTW: without making any changes, I did notice labels work as long as they are on the same line as code. So this would work just fine

```asm
mylabel: ld a, 1
```

But this would not
```
mylabel:
    ld a, 1
```

**Comment by andrivet** [comment]
Thanks for the messages. I will do a major update of the ZX81 Debugger once the upstream (Dezog) next version is released. It will fix this issue.
