### ISSUE TITLE
Emulator at 99% before starting

### ISSUE THREAD

**Issue by bru65pag** [andrivet/ZX81-Debugger#9]
I'm running version 2.0.1 on Ubuntu 2024. Tried to downgrade to 1.3.1, but the issue is the same.

When I start debugging, the emulatot CPU runs at 99%, and things are very slow.

I noticed the following message in the terminal: 
_**[{ "resource": "/home/bruno/i_chatgpt.sld", "owner": "ZX81 Debugger", "severity": 4, "message": "The assembler file is missing the 'SLDOPT COMMENT WPMEM, LOGPOINT, ASSERTION' statement. Use of WPMEM, LOGPOINT, ASSERTION is not possible.", "source": "X81 Debugger", "startLineN**_

The content of the assembly file is:
    device zx81
debut:
    ld a,-1
    inc a
    ld a,0
jp debut

Zero clue as to what can cause the problem. It was working fine two days ago on the same assembly file.

**Comment by bru65pag** [comment]
Thanks for your feedback.
The emulation became much slower  a few days ago. This is still the case today. Some ubuntu updates occured, but I can't really link this to what happens.
Here is a video of the system monitoring, with VSCode, starting the debugger, and moving the black square on the screen (the $ moves independently). CPU reaches 100%. I find this strange. Again, exact same code was running much faster previously.
[Screencast from 2024-11-30 21-23-29.webm](https://github.com/user-attachments/assets/87ae49ec-b3b4-431f-8f03-5f4524971fcb)
Any suggestion to find what's wrong is welcome. I really can't tell where this is coming from, and I'm a bit relunctant to fully reinstall my machine...

**Comment by andrivet** [comment]
This could be due to another extension you have installed.

**Comment by bru65pag** [comment]
I am closing this, at behavior is back to normal. Definitely not a ZX-81 debugger issue, but no clue about what caused this to slow down.
Thanks for taking the time spent and apologize
